### ISSUE TITLE
Cannot upload

### ISSUE THREAD

**Issue by eladgel** [EmergeTools/emerge-upload-action#6]
It says the event type is unsupported.
This is the same event for both android and ios
![image](https://user-images.githubusercontent.com/412137/235285858-b549bf90-d7ad-459f-b8a9-8327b588e4d6.png)

**IOS**
![image](https://user-images.githubusercontent.com/412137/235285904-b1bf3ab3-5e8d-4ba4-804a-0f2e757a19ce.png)
![image](https://user-images.githubusercontent.com/412137/235285831-aefa2a66-f6df-477a-ae35-eaa4b4cd00b4.png)

**ANDROID**
![image](https://user-images.githubusercontent.com/412137/235285940-a378a4e1-c956-4248-b517-3c862c63025d.png)
![image](https://user-images.githubusercontent.com/412137/235285834-01c969f2-2ca7-45d8-845e-475084499afe.png)

**Comment by eladgel** [comment]
On IOS this is what I get
![image](https://user-images.githubusercontent.com/412137/235287837-aca007b2-cc26-410a-86c1-8ad67fb68768.png)

**Comment by rbro112** [comment]
Hey @eladgel, thanks for letting us know about this. Currently we don't support the `release` action trigger but I can look into adding this soon. 

For now, using the `pull_request` or `push` action triggers should work.

**Comment by NicoHinderling** [comment]
hey @eladgel , I tried to implement this, but the problem is that we can't get the BASE_SHA value from github's release trigger event, which we consider required. 

I know it's been a while but just wanted to close the loop here. I hope you've been able to find another approach since! 🙏 If not, please let me know
